on:
  push:
    branches:
      - 'main'

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - run: cat $GOOGLE_APPLICATION_CREDENTIALS
      - run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json
      - run: ./gradlew assembleDebug
      - run: npm install -g firebase-tools
      - run: |
          firebase appdistribution:distribute \
              --app '${{ secrets.FIREBASE_APP_ID }}' \
              ./app/build/outputs/apk/debug/app-debug.apk